#pragma checksum "..\..\..\..\View\ManagerView.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "6836D924A5703B4666B2EEC775F9155A33B68DBD"
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using PRBD_Framework;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using prbd_2122_g19.View;
using prbd_2122_g19.ViewModel;


namespace prbd_2122_g19.View {
    
    
    /// <summary>
    /// ManagerView
    /// </summary>
    public partial class ManagerView : PRBD_Framework.WindowBase, System.Windows.Markup.IComponentConnector {
        
        
        #line 12 "..\..\..\..\View\ManagerView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal prbd_2122_g19.ViewModel.ManagerViewModel vm;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\..\..\View\ManagerView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal PRBD_Framework.MyTabControl tabControl;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\..\View\ManagerView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem ManagerTab;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\..\..\View\ManagerView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal PRBD_Framework.MyDataGrid gridAccesses;
        
        #line default
        #line hidden
        
        
        #line 79 "..\..\..\..\View\ManagerView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TESTTab;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "5.0.13.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/prbd_2122_g19;component/view/managerview.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\View\ManagerView.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "5.0.13.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 10 "..\..\..\..\View\ManagerView.xaml"
            ((prbd_2122_g19.View.ManagerView)(target)).KeyDown += new System.Windows.Input.KeyEventHandler(this.WindowBase_KeyDown);
            
            #line default
            #line hidden
            return;
            case 2:
            this.vm = ((prbd_2122_g19.ViewModel.ManagerViewModel)(target));
            return;
            case 3:
            
            #line 29 "..\..\..\..\View\ManagerView.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.MenuLogout_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.tabControl = ((PRBD_Framework.MyTabControl)(target));
            return;
            case 5:
            this.ManagerTab = ((System.Windows.Controls.TabItem)(target));
            return;
            case 6:
            this.gridAccesses = ((PRBD_Framework.MyDataGrid)(target));
            return;
            case 7:
            this.TESTTab = ((System.Windows.Controls.TabItem)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

